name: pr

on:
  schedule:
   - cron: '10 15 * * *'

  
jobs:
  build-registry:
    name: 'Build Asset Registry'
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: create pull request
        run: gh pr create -B main -H test_pr_branch --title 'Merge test_pr_branch into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
