name: pr

on:
  schedule:
   - cron: '45 15 * * *'
  
jobs:
  build-registry:
    name: 'Build Asset Registry'
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            ref: ${{ github.head_ref }}
        
        - name: Set Node.js 16.x
          uses: actions/setup-node@v3
          with:
            node-version: 16.x
        
        - name: Install deps
          run: yarn install
    
        # remove previous assets registry
        - run: rm registry.json
    
        # rebuild assets registry
        - run: yarn start
    
        - name: pull-request
          uses: repo-sync/pull-request@v2
          with:
            destination_branch: "develop"
            github_token: ${{ secrets.GITHUB_TOKEN }}
            pr_label: "feature, automated pr"
            pr_title: "[Example] Simple demo"