name: pr

on:
  schedule:
   - cron: '30 13 * * *'

  
jobs:
  create-pr:
      name: Create PR
      runs-on: ubuntu-latest

      permissions:
        contents: write
        pull-requests: write
      steps:     
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
        # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: bot-auto-update-registry
          title: 'chore: update asset registry'
