name: pr

on:
  schedule:
   - cron: '45 16 * * *'
  
jobs:
  build-registry:
    name: 'Create PR'
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      
      - uses: actions/checkout@v4

      - run: touch test.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: bot-auto-update-registry
          title: 'chore: update asset registry'