name: pr

on:
  schedule:
   - cron: '35 15 * * *'
  
jobs:
  build-registry:
    name: 'Build Asset Registry'
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - name: pull-request
          uses: repo-sync/pull-request@v2
          with:
            destination_branch: "develop"
            github_token: ${{ secrets.GITHUB_TOKEN }}
            pr_label: "feature, automated pr"
            pr_title: "[Example] Simple demo"